"""Adiciona link de viagem ao item da folha de pagamento

Revision ID: 0e7c8d09080e
Revises: acc3d0f2471c
Create Date: 2025-08-16 22:49:24.221029

"""
from alembic import op
import sqlalchemy as sa
# ▼▼▼ ADICIONE ESTAS IMPORTAÇÕES ▼▼▼
import uuid
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '0e7c8d09080e'
down_revision = 'acc3d0f2471c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- INÍCIO DO CÓDIGO DE CORREÇÃO DE DADOS (public_tracking_token) ---
    viagem_table = table('viagem',
        column('id', sa.Integer),
        column('public_tracking_token', sa.String(36))
    )
    conn = op.get_bind()
    viagens_sem_token = conn.execute(
        viagem_table.select().where(viagem_table.c.public_tracking_token == None)
    ).fetchall()
    for viagem in viagens_sem_token:
        token = str(uuid.uuid4())
        conn.execute(
            viagem_table.update().where(viagem_table.c.id == viagem.id).values(public_tracking_token=token)
        )
    # --- FIM DO CÓDIGO DE CORREÇÃO ---

    # ▼▼▼ CORREÇÃO DO NOME DA TABELA ▼▼▼
    # Trocado de 'folha_pagamento' para 'item_folha_pagamento'
    with op.batch_alter_table('item_folha_pagamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viagem_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_item_folha_viagem', 'viagem', ['viagem_id'], ['id'])

    # O resto dos comandos gerados estava correto e é mantido.
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumo_medio_km_l', sa.Float(), nullable=True))

    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_toneladas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('custo_motorista_variavel', sa.Float(), nullable=True))
        batch_op.alter_column('public_tracking_token',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.alter_column('public_tracking_token',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('custo_motorista_variavel')
        batch_op.drop_column('peso_toneladas')

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_column('consumo_medio_km_l')

    # ▼▼▼ CORREÇÃO DO NOME DA TABELA TAMBÉM NO DOWNGRADE ▼▼▼
    with op.batch_alter_table('item_folha_pagamento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_folha_viagem', type_='foreignkey')
        batch_op.drop_column('viagem_id')

    # ### end Alembic commands ###