"""Corrige tipo da FK em LancamentoNotaFiscal e recria a tabela

Revision ID: 0f97808c7364
Revises: 4d08953d8f4b
Create Date: 2025-08-30 14:23:38.123123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f97808c7364'
down_revision = '4d08953d8f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado_digital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.drop_constraint('certificado_digital_empresa_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_certificado_digital_principal'), ['principal'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado_digital', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificado_digital_principal'))
        batch_op.create_unique_constraint('certificado_digital_empresa_id_key', ['empresa_id'])
        batch_op.drop_column('principal')

    # ### end Alembic commands ###
