"""Corrige tipo da foreign key em lancamento_nota_fiscal

Revision ID: 1baa7f9b62e8
Revises: 
Create Date: 2025-08-26 21:31:33.939369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1baa7f9b62e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lancamento_nota_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nfe_importada_chave_acesso', sa.String(length=44), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=False),
    sa.Column('emitente_cnpj', sa.String(length=14), nullable=False),
    sa.Column('emitente_nome', sa.String(length=255), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status_pagamento', sa.String(length=20), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('data_lancamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['nfe_importada_chave_acesso'], ['nfe_importada.chave_acesso'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamento_nota_fiscal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamento_nota_fiscal_chave_acesso'), ['chave_acesso'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_nota_fiscal_data_vencimento'), ['data_vencimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_nota_fiscal_status_pagamento'), ['status_pagamento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_nota_fiscal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamento_nota_fiscal_status_pagamento'))
        batch_op.drop_index(batch_op.f('ix_lancamento_nota_fiscal_data_vencimento'))
        batch_op.drop_index(batch_op.f('ix_lancamento_nota_fiscal_chave_acesso'))

    op.drop_table('lancamento_nota_fiscal')
    # ### end Alembic commands ###
