"""Cria tabela motorista e adiciona coluna categoria em veiculo

Revision ID: 279620fb675c
Revises: 
Create Date: 2025-06-07 15:55:16.938554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279620fb675c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('pessoa_tipo', sa.String(length=10), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=9), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('cnh', sa.String(length=11), nullable=False),
    sa.Column('validade_cnh', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('anexos', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('motorista', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motorista_cnh'), ['cnh'], unique=True)
        batch_op.create_index(batch_op.f('ix_motorista_cpf_cnpj'), ['cpf_cnpj'], unique=True)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('idioma', sa.String(length=20), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_phone', sa.String(length=11), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=7), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('km_rodados', sa.Float(), nullable=True),
    sa.Column('ultima_manutencao', sa.Date(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veiculo_placa'), ['placa'], unique=True)

    op.create_table('convite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convite_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_convite_token'), ['token'], unique=True)

    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('valor_recebido', sa.Float(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('endereco_saida', sa.String(length=200), nullable=False),
    sa.Column('endereco_destino', sa.String(length=200), nullable=False),
    sa.Column('distancia_km', sa.Float(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('duracao_segundos', sa.Integer(), nullable=True),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viagem_status'), ['status'], unique=False)

    op.create_table('custo_viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=False),
    sa.Column('combustivel', sa.Float(), nullable=True),
    sa.Column('pedagios', sa.Float(), nullable=True),
    sa.Column('alimentacao', sa.Float(), nullable=True),
    sa.Column('hospedagem', sa.Float(), nullable=True),
    sa.Column('outros', sa.Float(), nullable=True),
    sa.Column('descricao_outros', sa.String(length=300), nullable=True),
    sa.Column('anexos', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagem.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viagem_id')
    )
    op.create_table('destino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destino')
    op.drop_table('custo_viagem')
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viagem_status'))

    op.drop_table('viagem')
    with op.batch_alter_table('convite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convite_token'))
        batch_op.drop_index(batch_op.f('ix_convite_email'))

    op.drop_table('convite')
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculo_placa'))

    op.drop_table('veiculo')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    with op.batch_alter_table('motorista', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motorista_cpf_cnpj'))
        batch_op.drop_index(batch_op.f('ix_motorista_cnh'))

    op.drop_table('motorista')
    # ### end Alembic commands ###
