"""Adiciona a coluna usuario_id na tabela Cobranca

Revision ID: 505dcd30935f
Revises: 
Create Date: 2025-09-25 21:38:10.219370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505dcd30935f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_fluxo_caixa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centro_custo_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lancamento_fluxo_caixa_centro_custo_id'), ['centro_custo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_fluxo_caixa_unidade_negocio_id'), ['unidade_negocio_id'], unique=False)
        batch_op.create_foreign_key(None, 'centro_custo', ['centro_custo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_fluxo_caixa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lancamento_fluxo_caixa_unidade_negocio_id'))
        batch_op.drop_index(batch_op.f('ix_lancamento_fluxo_caixa_centro_custo_id'))
        batch_op.drop_column('centro_custo_id')

    # ### end Alembic commands ###
