"""Adiciona relacao entre NFeImportada e CertificadoDigital

Revision ID: 61d2b152822a
Revises: 0f97808c7364
Create Date: 2025-08-30 17:59:48.172332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d2b152822a'
down_revision = '0f97808c7364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfe_importada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificado_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nfe_importada_certificado_id'), ['certificado_id'], unique=False)
        batch_op.create_foreign_key(None, 'certificado_digital', ['certificado_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfe_importada', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_nfe_importada_certificado_id'))
        batch_op.drop_column('certificado_id')

    # ### end Alembic commands ###
