"""Adiciona a coluna usuario_id na tabela Cobranca

Revision ID: 6cfec9bbcf16
Revises: 
Create Date: 2025-09-19 23:19:29.976367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfec9bbcf16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rateio_veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lancamento_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('valor_rateado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento_fluxo_caixa.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rateio_veiculo')
    with op.batch_alter_table('lancamento_fluxo_caixa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tem_rateio', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_fluxo_caixa', schema=None) as batch_op:
        batch_op.drop_column('tem_rateio')

    op.create_table('rateio_veiculo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lancamento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('veiculo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_rateado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('percentual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento_fluxo_caixa.id'], name='rateio_veiculo_lancamento_id_fkey'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], name='rateio_veiculo_veiculo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rateio_veiculo_pkey')
    )
    op.drop_table('rateio_veiculos')
    # ### end Alembic commands ###
