"""Criacao inicial da base de dados com estrutura correta

Revision ID: 7735664994d3
Revises: 
Create Date: 2025-08-13 23:59:41.705321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7735664994d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('logradouro',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=11),
               nullable=False)

    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_em_estoque', sa.FLOAT(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ponto_ressuprimento', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.drop_column('ponto_ressuprimento')
        batch_op.drop_column('quantidade_em_estoque')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('logradouro',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
