"""Adiciona a coluna usuario_id na tabela Cobranca

Revision ID: 9bb508c67d35
Revises: b5f469f11a03
Create Date: 2025-09-28 15:18:53.666491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb508c67d35'
down_revision = 'b5f469f11a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_transportado', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.drop_column('material_transportado')

    # ### end Alembic commands ###
