"""Adiciona funcionalidade de folha de pagamento

Revision ID: acc3d0f2471c
Revises: 1fc042f62176
Create Date: 2025-08-15 21:51:29.895877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc3d0f2471c'
down_revision = '1fc042f62176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folha_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('salario_base_registro', sa.Float(), nullable=True),
    sa.Column('total_proventos', sa.Float(), nullable=True),
    sa.Column('total_descontos', sa.Float(), nullable=True),
    sa.Column('salario_liquido', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('meio_pagamento', sa.String(length=50), nullable=True),
    sa.Column('comprovante_url', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('motorista_id', 'mes_referencia', 'ano_referencia', name='_motorista_mes_ano_uc')
    )
    with op.batch_alter_table('folha_pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folha_pagamento_ano_referencia'), ['ano_referencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_folha_pagamento_mes_referencia'), ['mes_referencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_folha_pagamento_status'), ['status'], unique=False)

    op.create_table('item_folha_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folha_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['folha_pagamento_id'], ['folha_pagamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_folha_pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_folha_pagamento_tipo'), ['tipo'], unique=False)

    with op.batch_alter_table('motorista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salario_base', sa.Float(), nullable=True))

    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_tracking_token', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.drop_column('public_tracking_token')

    with op.batch_alter_table('motorista', schema=None) as batch_op:
        batch_op.drop_column('salario_base')

    with op.batch_alter_table('item_folha_pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_folha_pagamento_tipo'))

    op.drop_table('item_folha_pagamento')
    with op.batch_alter_table('folha_pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folha_pagamento_status'))
        batch_op.drop_index(batch_op.f('ix_folha_pagamento_mes_referencia'))
        batch_op.drop_index(batch_op.f('ix_folha_pagamento_ano_referencia'))

    op.drop_table('folha_pagamento')
    # ### end Alembic commands ###
