"""Adiciona link de viagem ao item da folha de pagamento

Revision ID: b32f6f013134
Revises: 0e7c8d09080e
Create Date: 2025-08-16 23:30:43.411542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32f6f013134'
down_revision = '0e7c8d09080e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folha_pagamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viagem_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'viagem', ['viagem_id'], ['id'])

    with op.batch_alter_table('item_folha_pagamento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_folha_viagem', type_='foreignkey')
        batch_op.drop_column('viagem_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_folha_pagamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viagem_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_item_folha_viagem', 'viagem', ['viagem_id'], ['id'])

    with op.batch_alter_table('folha_pagamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('viagem_id')

    # ### end Alembic commands ###
