"""Adiciona a coluna usuario_id na tabela Cobranca

Revision ID: b54263f58380
Revises: 6cfec9bbcf16
Create Date: 2025-09-22 00:27:44.376464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54263f58380'
down_revision = '6cfec9bbcf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_fluxo_caixa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meio_pagamento', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_fluxo_caixa', schema=None) as batch_op:
        batch_op.drop_column('meio_pagamento')

    # ### end Alembic commands ###
