"""Adiciona a coluna usuario_id na tabela Cobranca

Revision ID: b5f469f11a03
Revises: 505dcd30935f
Create Date: 2025-09-26 19:29:40.970125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f469f11a03'
down_revision = '505dcd30935f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_administrativo', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.create_index(batch_op.f('ix_veiculo_is_administrativo'), ['is_administrativo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculo_is_administrativo'))
        batch_op.drop_column('is_administrativo')

    # ### end Alembic commands ###
