"""Corrige tipo da FK em LancamentoNotaFiscal e recria a tabela

Revision ID: b68ff80eb4f2
Revises: 1baa7f9b62e8
Create Date: 2025-08-29 21:41:10.578813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68ff80eb4f2'
down_revision = '1baa7f9b62e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_nota_fiscal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcela_numero', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parcela_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lancamento_pai_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'lancamento_nota_fiscal', ['lancamento_pai_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_nota_fiscal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('lancamento_pai_id')
        batch_op.drop_column('parcela_total')
        batch_op.drop_column('parcela_numero')

    # ### end Alembic commands ###
