"""Adicionar campo cnpj_consultado

Revision ID: cdd9a4d472cf
Revises: 
Create Date: 2025-10-01 13:26:27.337211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd9a4d472cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfe_importada', schema=None) as batch_op:
        batch_op.drop_constraint('nfe_importada_certificado_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'certificado_digital', ['certificado_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfe_importada', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nfe_importada_certificado_id_fkey', 'certificado_digital', ['certificado_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
